#:schema node_modules/wrangler/config-schema.json
name = "sublink-wk"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "bd610bd2655a4a20a51c396165877bfe" }
]

[assets]
directory = "./public"
